# Generated by Django 6.0.1 on 2026-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
