# Generated by Django 6.0.1 on 2026-02-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0002_sports_sportsman_sport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sports',
            options={'ordering': ['-name'], 'verbose_name': 'Sport'},
        ),
        migrations.AlterModelOptions(
            name='sportsman',
            options={'ordering': ['-title'], 'verbose_name': 'Sport news', 'verbose_name_plural': 'Sport news'},
        ),
        migrations.AlterField(
            model_name='sports',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='The name of sport'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
    ]
